### ISSUE TITLE
Inconsistent type checking for custom Notification

### ISSUE THREAD

**Issue by jbraband** [spatie/laravel-failed-job-monitor#46]
When creating a custom Notification class and setting it in the config, the custom class must extend Spatie\FailedJobMonitor\Notification according to line 34 of FailedJobNotifier.php

https://github.com/spatie/laravel-failed-job-monitor/blob/90fa5f9b8a977e85d9c97e82629d02d4f260db24/src/FailedJobNotifier.php#L34

The exception that is thrown in InvalidConfiguration.php however specifies that the custom Notification class should extend Illuminate\Notifications\Notification

https://github.com/spatie/laravel-failed-job-monitor/blob/90fa5f9b8a977e85d9c97e82629d02d4f260db24/src/Exceptions/InvalidConfiguration.php#L12-L13

The test in the package for this uses a dummy AnotherNotification class which extends Spatie\FailedJobMonitor\Notification and therefore passes.

When using this library however, I saw the InvalidConfiguration.php exception and extend my custom Notification class from Illuminate\Notifications\Notification and a failed job sits in an endless loop of failure notifications.

which way would spatie prefer to fix this? Change the InvalidConfiguration.php exception message to match the actual restriction? or change the restriction check in FailedJobNotifier.php to match the exception message?

I can provide a pull request either way.

**Comment by w0rd-driven** [comment]
I just ran into this myself. How I corrected it internally was to add `use Illuminate\Notifications\Notification;` to the top of `src/FailedJobNotifier.php` since my understanding of the readme was that we're doing something like `artisan make:notification HorizonFailedJob` to create our custom notification. What I did from there was copy the body of the existing Notification class, complete with getEvent/setEvent.

I think that because the internals rely on the setEvent method, that extending `Spatie\FailedJobMonitor\Notification` makes more sense. This is what the test seems to suggest. I think the problem is that the readme is a little ambiguous if we take this approach. If we are to take this route then you are correct that `InvalidConfiguration.php` should change to match.

I'm taking the approach not to use the Iluminate class because I don't have to wait on a PR for it to work but it would be a good idea to shore up the code if this is the more "blessed" way to customize your notifications.
